version: "3"

services:
  database:
    image: postgres:latest
    container_name: database
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always