version: "3"

services:
  database:
    image: postgres:latest
    container_name: shortner_database
    env_file: .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  
  api:
    build: .
    container_name: shortner_app
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - database